### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 2339

### ISSUE THREAD

**Issue by tchristian1103** [o0shojo0o/ioBroker.opendtu#105]
### What happened?

Fehler im Log:
opendtu.0 | 2023-10-02 16:09:04.096 | error | SyntaxError: Unexpected token u in JSON at position 2339

opendtu.0 | 2023-10-02 16:57:05.134 | error | SyntaxError: Unexpected token u in JSON at position 6664

OpenDTU v23.9.18
ioBroker.opendtu: v1.0.0

### What did you expect to happen?

No error in Log.

### OpenDTU version

23.9.18

### Adapter version

1.0.0

### Log

opendtu.0 | 2023-10-02 16:09:04.096 | error | SyntaxError: Unexpected token u in JSON at position 2339
opendtu.0 | 2023-10-02 16:57:05.134 | error | SyntaxError: Unexpected token u in JSON at position 6664

**Comment by o0shojo0o** [comment]
Sonst bitte einmal von Git installieren und den Adapter auf Debug Log stellen. 
Dann wird in Fehlerfall das vermeintliche JSON im Log mit ausgegeben.

**Comment by tchristian1103** [comment]
Hab auf Debug gestellt, das Log sieht trotzdem identisch aus. Die "Zeile" ändert sich aber scheinbar immer:

opendtu.0 | 2023-10-03 08:36:29.138 | error | SyntaxError: Unexpected token C in JSON at position 2607

**Comment by o0shojo0o** [comment]
Du solltest auch den Adapter aus dem Git hier vorher installieren. 
In der Git Version habe ich an der entsprechenden Stelle ein Debug Log hinzugefügt.

**Comment by tchristian1103** [comment]
So, vielleicht das hier?

opendtu.0 | 2023-10-04 05:29:03.122 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-10-04 05:29:01.976 | debug | Start try again in 1 seconds...
opendtu.0 | 2023-10-04 05:29:01.928 | debug | Websocket error: RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
