### ISSUE TITLE
The adapter is not connecting (login) to OpenDTU.

### ISSUE THREAD

**Issue by gitbreiti** [o0shojo0o/ioBroker.opendtu#116]
### What happened?

I noticed that the adapter is no longer registering correctly with OpenDTU (as seen in the screenshot). When I manually enter the username and password, everything works again. Unfortunately, it doesn't seem to work automatically anymore.
![Screenshot 2023-12-13 105143](https://github.com/o0shojo0o/ioBroker.opendtu/assets/45651354/859be6c1-ed56-4877-910c-cff31255bfcc)

While testing, I also observed that the entered IP address in the adapter doesn't matter, it still turns green. However, in the OpenDTU section in ioBroker, nothing is displayed.

### OpenDTU version

23.11.16

### Adapter version

1.0.1

**Comment by o0shojo0o** [comment]
You mean that the adapter does not log in to the web interface? 
It has never done that, and it won't. 
The user data is used for the API.

**Comment by gitbreiti** [comment]
I'm sorry, I misunderstood it then! I will test it again tomorrow and then provide feedback.
Perhaps there was no sun at that moment, and that's why nothing was transmitted.

**Comment by gitbreiti** [comment]
I'm sorry, I misunderstood it then! I will test it again tomorrow and then provide feedback.
Perhaps there was no sun at that moment, and that's why nothing was transmitted.
