### ISSUE TITLE
does not work fully with new version of OpenDTU anymore

### ISSUE THREAD

**Issue by chris299** [o0shojo0o/ioBroker.opendtu#129]
### What happened?

values ac.phase_1.yieldday and yieldtotal are not updated in IOBroker anymore, most likely due to breaking changes in the API, see https://github.com/tbnobody/OpenDTU/releases/tag/v24.2.12

the inverters need to be asked individually by serial number now, instead of all at once.... see https://github.com/tbnobody/OpenDTU/commit/c27ecc3620f656fbdfaa7e9f0f3deca6a371a373

### OpenDTU version

24.2.12

### Adapter version

1.0.1

**Comment by o0shojo0o** [comment]
Note to self:
https://github.com/tbnobody/OpenDTU/discussions/1463#discussioncomment-8303819

**Comment by o0shojo0o** [comment]
Please test this dev branch https://github.com/o0shojo0o/ioBroker.opendtu/tree/new-websoket-structure-%23129

**Comment by chris299** [comment]
@o0shojo0o vielen Dank für die Anpassung und Dein Engagement.
Aber eine blöde Frage: wie installier ich denn den Fork? im Admin sehe ich da anscheinend nur den main-fork, oder?
![grafik](https://github.com/o0shojo0o/ioBroker.opendtu/assets/33319001/a0497aea-45d1-462d-9578-fdd512936f18)

**Comment by o0shojo0o** [comment]
Du musst den Link in **Benutzerdefiniert** einfügen.

**Comment by chris299** [comment]
danke. bin gespannt, wie das morgen abend aussieht 👍 
![grafik](https://github.com/o0shojo0o/ioBroker.opendtu/assets/33319001/70e95579-ad33-4a0a-b395-56da9bf4a855)

**Comment by o0shojo0o** [comment]
Aber aufgepasst die Datenpunkte habe sich verschoben! 
Diese sind jetzt unter den Inverter direkt.

**Comment by chris299** [comment]
danke. habs grad gesehen 😃

**Comment by chris299** [comment]
@o0shojo0o sieht sehr gut aus. 👍 
könnte man bei update des Adapters die alten Datenpunkte nullen (nicht löschen)? die Werte dort machen ja keinen Sinn mehr....

**Comment by o0shojo0o** [comment]
> könnte man bei update des Adapters die alten Datenpunkte nullen (nicht löschen)? die Werte dort machen ja keinen Sinn

Ja das würde gehen, aber ich bin da grundsätzlich sehr vorsichtig, denn so würde alles was an den Datenpunkt hängt ggf. gelöscht. 
Darum sollte man das schon selbst machen, das aufwand ist ja vertretbar.
