### ISSUE TITLE
immer wieder 0W werte zwischendurch

### ISSUE THREAD

**Issue by chris299** [o0shojo0o/ioBroker.opendtu#142]
### What happened?

seit zwei oder drei Versionen von openDTU sehe ich in der history der DP zu Power immer wieder 0W Werte, die natürlich nicht richtig sind. Und so weit ich das sehe auch nicht von der OpenDTU kommen, sondern wohl mit einem Missverständnis der beiden System untereinander zusammenhängen...
interessanterweise nur bei einem meiner beiden HMS...

![grafik](https://github.com/o0shojo0o/ioBroker.opendtu/assets/33319001/f91cf970-62e7-4168-8835-0ea31fe61ac2)

![grafik](https://github.com/o0shojo0o/ioBroker.opendtu/assets/33319001/0006474d-6a29-49a8-acff-e2d13f00ef74)

### What did you expect to happen?

keine 0W Werte wenn die Sonne scheint und OpenDTU >0W anzeigt

### How to reproduce it (minimal and precise)

passiert derzeit jeden Tag sporadisch...

### OpenDTU version

24.4.24

### Adapter version

git work in progress

**Comment by chris299** [comment]
da gibt es wohl diverse Bugs in der aktuellen openDTU Version, siehe auch https://github.com/tbnobody/OpenDTU/issues/1959#issuecomment-2094928534

**Comment by chris299** [comment]
mit der 24.5.6 habe ich das bisher nicht wieder gesehen. ich mache das issue daher mal zu.

**Comment by chris299** [comment]
@o0shojo0o mit der 24.5.6 kam es dann doch wieder. auch mit der 24.6.10. sehe ich das Phänomen und es scheint ein Adapter-Problem zu sein.
Ich habe jetzt mal selber mit einem API-Test Tool "nachgesehen" was die OpenDTU so liefert, wenn der Adapter 0 W in die Datenpunkte schreibt: von der OpenDTU kommen im API keine 0 Werte! 
Es scheint damit zu zu tun zu haben, dass sich die API-antwort über einen längeren Zeitraum nicht verändert, weil die OpenDTU keinen Kontakt zum Inverter bekommt (warum auch immer) OpenDTU liefert dann beim Polling immer weiter den alten Wert.
In der GUI sieht man dann eine recht lange Zeit ohne Aktualisierung:
![grafik](https://github.com/o0shojo0o/ioBroker.opendtu/assets/33319001/697cd7b3-c416-4c87-813f-b4c9fa94d694)
aber die Werte im Adapter-DP "oszilieren" währenddessen:
![grafik](https://github.com/o0shojo0o/ioBroker.opendtu/assets/33319001/f00718ea-5c9b-40f7-a384-c6f588907f30)

**Comment by Carsten1987** [comment]
Sieht mir aus wie #97

**Comment by chris299** [comment]
@Carsten1987 danke für den Hinweis, das probiere ich gern aus.
