### ISSUE TITLE
Improve configuration of OpenDTU address

### ISSUE THREAD

**Issue by hombach** [o0shojo0o/ioBroker.opendtu#19]
Great new adapter!!! Bring this to latest repo! Works good!

**Describe the bug**  
Not really a bug - just a proposal - text "OpentDU IP-Adresse" might be more clear to understand than "Web-UI-Adresse" 
Another proposal: Add some code to get an note for the user when adding something other than an "plain IP" e.g.:

_this.log.info(`IP address found in config: ${this.config.ipaddress}`);
            // Validate IP address ...
            if (!(/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/.test(this.config.ipaddress))) {
                this.log.error(`You have entered an invalid IP address! ${this.config.ipaddress}`)
            }_

<img width="226" alt="image" src="https://user-images.githubusercontent.com/63002482/225102395-93ec1065-42b0-4c14-ad08-a4ae9eb412fe.png">

**Versions:**  
 - Adapter version: 0.1.2

**Comment by o0shojo0o** [comment]
I can't do that because some users use a proxy to connect to the WebUi via https, and there no IP is used anymore.
