### ISSUE TITLE
Kennwort mit Sonderzeichen (#)

### ISSUE THREAD

**Issue by Schlonsy** [o0shojo0o/ioBroker.opendtu#35]
Hallo,

bei der Inbetriebnahme von iobroker.opendtu mit der aktuellen Version der openDTU (v23.4.17) ist mir aufgefallen, das ich mit dem ursprünglichen Kennwort mit Sonderzeichen keine Verbindung herstellen konnte. Durch einen anderen Beitrag bin ich auf die Idee gekommen, dass es an dem Sonderzeichen liegen könnte. Nachdem ich das openDTU Kennwort entsprechend geändert hatte ging es dann. Das Problem scheint auf dieser Seite zu liegen, da sich der WebSocket in websocketController.js zuvor über eine ungültige URL beschwert hat.

Viele Grüße,
   Karsten

**Comment by Schlonsy** [comment]
Still unfixed issue

**Comment by o0shojo0o** [comment]
Bitte einmal von GitHub installieren und testen :) 
Auch bitte ob sich die Leistung verstellen lässt.

**Comment by o0shojo0o** [comment]
@Schlonsy konntest du schon testen?

**Comment by Schlonsy** [comment]
Moin Dennis, ich hoffe, ich schaffe es dies Wochenende.Viele Grüße, Karsten
-------- Ursprüngliche Nachricht --------Von: Dennis Rathjen ***@***.***> Datum: 04.09.23  17:25  (GMT+01:00) An: "o0shojo0o/ioBroker.opendtu" ***@***.***> Cc: Schlonsy ***@***.***>, Mention ***@***.***> Betreff: Re: [o0shojo0o/ioBroker.opendtu] Kennwort mit Sonderzeichen (#)
  (Issue #35) 
@Schlonsy konntest du schon testen?

**Comment by Schlonsy** [comment]
Hallo Dennis,
grobe Fehlbedienung von Emails meinerseits. Meine Antwort scheint im nirvana verschwunden zu sein.
Ich habe deine Änderung getestet und bin mir gerade nicht sicher was du mit "Auch bitte testen ob sich die Leistung verstellen lässt." meinst. Ich bekomme zwar Daten von der DTU jedoch ist der Button zur Einstellung der Leistung deaktiviert.
Um sicherzustellen, dass ich beim Update des Adapters nichts falsch gemacht habe: wie muss ich vorgehen und was soll, vom login abgesehen, sich genau ändern.
Ich danke dir für deine Geduld und gelobe schnelle Rückmeldung.
Viele Grüße,
   Karsten
