### ISSUE TITLE
openDTU API Änderung?

### ISSUE THREAD

**Issue by Schlonsy** [o0shojo0o/ioBroker.opendtu#36]
Hallo,

kann es sein, dass sich die API der openDTU geändert hat? In websocketController.js wird versucht der livestatus aus /livedata zu beziehen. Laut API-Dokument von openDTU (https://github.com/tbnobody/OpenDTU/blob/master/docs/Web-API.md) scheint der korrekte Pfad jedoch /api/livedata/status zu sein. 
Nachdem ist das probehalber mal entsprechend geändert habe konnte ich mit erfolgreich mit der openDTU verbinden. 

Hat sich da noch mehr geändert? Bisher bekomme ich noch keine Daten über meinen Wechselrichter.

Viele Grüße,
   Karsten

P.S.: ich bin gerade erst mit dem Wechselrichter gestartet und kenne mich somit nicht wirklich aus damit. Vielleicht habe ich auch einfach noch was übersehen. 

P.P.S.: das exception Handling scheint noch Raum für Verbesserungen zu haben ;-)

**Comment by o0shojo0o** [comment]
Nein das aktuelle OpenDTU Release hat keine  Breaking Changes die den Adapter betreffen.
Auch der api call auf den du dich beziehst wird nicht genutzt, den an dieser Stelle wird eine websocketverbindung genutzt und nicht die Web api.

Also kurz der Adapter läuft fehlerfrei mit dem aktuellen Release.

**Comment by Schlonsy** [comment]
Moin Dennis,vielen Dank für die schnelle Antwort. Dann bin ich hier also noch nicht so weit. Viele Grüße, Karsten
-------- Ursprüngliche Nachricht --------Von: Dennis Rathjen ***@***.***> Datum: 23.04.23  08:33  (GMT+01:00) An: "o0shojo0o/ioBroker.opendtu" ***@***.***> Cc: Schlonsy ***@***.***>, Author ***@***.***> Betreff: Re: [o0shojo0o/ioBroker.opendtu] openDTU API Änderung? (Issue #36) 
Nein das aktuelle OpenDTU Release hat keine  Breaking Changes die den Adapter betreffen.
Auch der api call auf den du dich beziehst wird nicht genutzt, den an dieser Stelle wird eine websocketverbindung genutzt und nicht die Web api.
Also kurz der Adapter läuft fehlerfrei mit dem aktuellen Release.

**Comment by Schlonsy** [comment]
Sorry, mein Fehler. Läuft wie versprochen.
