### ISSUE TITLE
cannot connect to OpenDTU

### ISSUE THREAD

**Issue by boergl** [o0shojo0o/ioBroker.opendtu#48]
Adapter Version 0.1.4
OpenDTU Version: v23.5.3
OpenDTU Chip: ESP32-D0WDQ5

**IOBroker Adapter Log** 
	2023-05-08 10:27:32.311	debug	getDTUData axios error: Error: getaddrinfo ENOTFOUND http
	2023-05-08 10:27:34.578	debug	Websocket error: Error: getaddrinfo ENOTFOUND http
	2023-05-08 10:27:34.578	debug	Start try again in 1 seconds...

**Comment by SirFlour** [comment]
strange. How is your setup? looks like the adress cannot be found (it is DNS error meaning address cannot be resolved). Did you maybe put in iobrokter the http with the Ip adress or should you use https? Can you access the opendtu via the ipaddress? Ioborker in a different ip-range than opendtu? :)

**Comment by boergl** [comment]
Network setups is complete flat. (Special IOT LAN) Both systems are in the same /24 subnet. 
IOBroker has 10.1.12.3
OpenDTU has 10.1.12.13

Yesterday I used the ip adress instead of dns. Today I tried it with DNS with the same result: 

opendtu.0
2023-05-09 09:43:44.601	debug	Start try again in 1 seconds...
opendtu.0
2023-05-09 09:43:44.601	debug	Websocket error: Error: getaddrinfo ENOTFOUND http
opendtu.0
2023-05-09 09:43:42.339	debug	getDTUData axios error: Error: getaddrinfo ENOTFOUND http

Yes, I can access the OpenDTU Web UI from the IOBroker Server. IOBroker is running on Windows.

Any Ideas?

**Comment by SirFlour** [comment]
not easy :/ How is your selection in iobroker? Maybe you selected http + ip but you need to select https + ip. also sometime on windows you have to set the network to private instead of public, to allow the devices to communicate with each other. However, maybe it is due to your password which contains special characters? that leads to a wrong link and might cause the error

**Comment by boergl** [comment]
I tried almost every possilbe option. http/https ip/dns 
password has no special characters, changed it also alreasy.
Windows is in private network mode, tried also to disable the firewall (makes no sense becuase IObroker wants to connect to opendtu but tried it anyway)
