### ISSUE TITLE
Adapter lost websocket connection

### ISSUE THREAD

**Issue by Xenon-s** [o0shojo0o/ioBroker.opendtu#52]
**Describe the bug**  
The adapter seems to constantly lose connection to the websocket. This is indicated firstly by the fact that messages keep appearing stating that it has reconnected and secondly by the fact that no new data keep appearing in the ioBroker. If you restart the adapter, everything works again.

**To Reproduce**  
-

**Screenshots & Logfiles**  
`
opendtu.0 | 2023-05-21 16:24:04.479 | info | Connect to OpenDTU over websocket connection.
-- | -- | -- | --
opendtu.0 | 2023-05-21 16:15:58.747 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:40:00.906 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:28:03.898 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:27:39.397 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:15:15.111 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:12:07.039 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:11:51.710 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 15:04:14.144 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:59:29.667 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:59:04.408 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:58:36.386 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:56:40.565 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:55:09.147 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:51:12.142 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:49:57.591 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:49:21.742 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:49:07.138 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:47:52.770 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:47:15.721 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:46:49.999 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:45:04.711 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:43:09.142 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:42:36.448 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:42:12.222 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:41:51.025 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:39:28.257 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:38:40.896 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:38:09.548 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:35:33.100 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:34:57.854 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:30:42.246 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:28:14.896 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:26:48.237 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:26:22.201 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:25:36.698 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:25:22.143 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:16:57.749 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:04:26.224 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:03:20.574 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:03:19.364 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 14:02:03.935 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:59:59.660 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:59:47.676 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:58:29.902 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:58:28.797 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:49:02.249 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:42:50.803 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:42:36.336 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:41:43.746 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:40:56.348 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:40:02.110 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:38:54.759 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:38:07.955 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:36:42.591 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:36:25.140 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:36:01.875 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:34:07.657 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:33:49.996 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:33:24.168 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:33:01.343 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:31:03.236 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:30:33.504 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:30:19.136 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:30:03.841 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:29:48.715 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:29:34.322 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:29:16.434 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:28:42.051 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:28:16.377 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:26:40.692 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:26:26.175 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:26:08.780 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:24:54.521 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:24:21.743 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:23:16.928 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:23:15.789 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:21:24.172 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:19:46.422 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:19:29.220 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:16:17.574 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:14:03.008 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:13:47.622 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:13:36.367 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:13:11.206 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:12:53.611 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:12:52.171 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:12:17.604 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:12:05.436 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:11:37.966 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:10:21.353 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 13:09:43.758 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 12:36:28.251 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 12:24:10.884 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 12:06:13.074 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 12:05:20.540 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 11:12:05.956 | info | Connect to OpenDTU over websocket connection.
opendtu.0 | 2023-05-21 11:12:05.776 | info | starting. Version 0.1.4 (non-npm: o0shojo0o/ioBroker.opendtu#e760893cdfe7623bdfc9c250aa6ee40f197c0023) in /opt/iobroker/node_modules/iobroker.opendtu, node: v18.16.0, js-controller: 4.0.24
opendtu.0 | 2023-05-21 11:12:02.082 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
opendtu.0 | 2023-05-21 11:12:02.081 | info | terminating
opendtu.0 | 2023-05-21 11:12:02.078 | info | Got terminate signal TERMINATE_YOURSELF
`

**Versions:**  
 - Adapter version: 0.1.4
 - JS-Controller version: 4.0.24
 - Node version: 18.1.6.0
 - Operating system: ubuntu 22.04

**Comment by o0shojo0o** [comment]
Please try the current version first.

**Comment by Xenon-s** [comment]
`
opendtu.0 | 2023-05-28 08:41:37.100 | warn | setInverterLimit axios error: Error: read ECONNRESET
-- | -- | -- | --
opendtu.0 | 2023-05-28 08:39:08.256 | warn | setInverterLimit axios error: Error: socket hang up
opendtu.0 | 2023-05-28 08:35:34.725 | warn | setInverterLimit axios error: Error: socket hang up
opendtu.0 | 2023-05-28 08:33:07.608 | warn | setInverterLimit axios error: Error: socket hang up
opendtu.0 | 2023-05-28 08:33:00.025 | warn | setInverterLimit axios error: Error: read ECONNRESET
opendtu.0 | 2023-05-28 08:21:03.492 | warn | setInverterLimit axios error: Error: read ECONNRESET
opendtu.0 | 2023-05-28 07:53:02.698 | warn | setInverterLimit axios error: Error: socket hang up
opendtu.0 | 2023-05-28 07:50:32.800 | warn | setInverterLimit axios error: Error: socket hang up
opendtu.0 | 2023-05-28 07:48:59.963 | warn | setInverterLimit axios error: Error: read ETIMEDOUT
opendtu.0 | 2023-05-28 07:48:06.716 | warn | setInverterLimit axios error: Error: connect ETIMEDOUT 192.168.0.45:80
opendtu.0 | 2023-05-28 07:47:17.369 | warn | setInverterLimit axios error: Error: socket hang up
opendtu.0 | 2023-05-28 07:45:37.216 | warn | setInverterLimit axios error: Error: connect ETIMEDOUT 192.168.0.45:80
opendtu.0 | 2023-05-28 07:43:40.476 | warn | setInverterLimit axios error: Error: connect ETIMEDOUT 192.168.0.45:80
opendtu.0 | 2023-05-28 07:43:05.661 | warn | setInverterLimit axios error: Error: connect ETIMEDOUT 192.168.0.45:80
`

I will build a second DTU and then run each inverter individually and test further
