### ISSUE TITLE
Opendtu Adapter setzt keinen Status _on und _off ab wie erwartet

### ISSUE THREAD

**Issue by OttiNC1** [o0shojo0o/ioBroker.opendtu#64]
Ein Beschreiben von power_on mit true schaltet den Inverter ein. Ein Beschreiben mit false schaltet den Inverter aus. Ist das so vorgesehen? Wozu ist der Datenpunkt "power_off"? Die beiden Datenpunkte sind offenbar keine "Taster" , wie erwartet. Wobei mir dieses Verhalten viel lieber ist!
Version 0.1.5
Nodejs:  v18.16.1

**Comment by o0shojo0o** [comment]
ist in der Version 0.1.6 behoben

**Comment by OttiNC1** [comment]
Habe die Version 0.1.6 installiert. Leider werden jetzt keine Datenpunkte in den "Objekten" erzeugt.

**Comment by o0shojo0o** [comment]
Ich denke das du da ein Einstellung Fehler hast, da meine 3 Instanzen laufen wie erwartet.
Sonst wäre auch ein Logauszug hilfreich.

**Comment by OttiNC1** [comment]
Dann muß es bei mir auch gehen. Werde den Fehler suchen. Zur Zeit finde ich den Adapter auf Github nicht (Repostery beta). Habe den Adapter gelöscht und will ihn neu installieren.

**Comment by o0shojo0o** [comment]
Das ist der Link -> https://github.com/o0shojo0o/ioBroker.opendtu

**Comment by OttiNC1** [comment]
Danke!

**Comment by OttiNC1** [comment]
Mein Fehler: falsche IP Adresse eingetragen! Geht jetzt wieder.

**Comment by OttiNC1** [comment]
Allerdings ist die Bedienung immer noch so wie vorher (letzte Version). ein "power_on" = true schaltet den Inverter ein, ein "power_on" = false schaltet den Inverter aus. Keine "Taster-Funktionalität.

**Comment by o0shojo0o** [comment]
Nein das sind Taster bitte nur mit True beschreiben!

**Comment by OttiNC1** [comment]
Das funktioniert ja aber nicht. Wenn das true des "power_on" durch ein true beim "power_off" rückgesetzt würde, dann wäre das ja OK. Passiert aber nicht. Ein gesetztes true bleibt stehen.

**Comment by OttiNC1** [comment]
Die Handbetätigung habe ich in VIS. Jeweils ein Button für ein und aus. Der toggelt immer bei Betätigung. Einmal Ein gesetzt, bleibt der Button so stehen, wenn ich den wieder aus schalte, setzt er "false".

**Comment by o0shojo0o** [comment]
Ich nutze die API vom OpenDTU Frontend, dort ist die Handhabung so vorgegeben, in Lovelace kann das so genutzt werden wenn eine bis das nicht kann sollte dort ein issues gemacht werden, da ioBroker diese Button zur Verwendung anbietet.

**Comment by OttiNC1** [comment]
Die API benutzt doch aber nicht den Adapter? VIS kann einen Impuls ausgeben, wenn ich den Bedien- Button auf "Taster" stelle. Beim 1x Drücken geht der Datenpunkt auf true und wieder zurück auf false. Und genau damit kann der Adapter nicht umgehen. 
Und er muß ja auf false zurückgehen, es gibt ja nur true und false, kein "inaktiv"

**Comment by o0shojo0o** [comment]
in der v 0.1.7 fange ich jetzt das **falsche** benutzen des Datenpunktes ab.

**Comment by OttiNC1** [comment]
Super! Jetzt kann ich mit zwei Tastern (Ein und Aus) den Hoymiles ein und ausschalten.
