### ISSUE TITLE
Nach Neustart vom Adapter bitte common.name nicht Ändern

### ISSUE THREAD

**Issue by Hirsch-DE** [o0shojo0o/ioBroker.opendtu#76]
Nach dem Neustart des Adapters wird der Name immer auf das Orginal geändert!
Bitte den Namen nicht ändern!

**Versions:**  
 - Adapter version: 0.1.7
 - JS-Controller version: 5.0.8
 - Node version: 18.17.0
 - Operating system: Debian buster

**Comment by o0shojo0o** [comment]
Der kommt doch aus der openDTU, da ist der zu konfigurieren.

Nicht im iob Objekt.

**Comment by Hirsch-DE** [comment]
Wo kann ich in der openDTU die Namen für
opendtu.0.total.power
opendtu.0.total.yieldday
opendtu.0.114190103421.ac.phase_1.yieldday
opendtu.0.114190103421.ac.phase_1.power

ändern?

22.07.2023 08:59:49 Dennis Rathjen ***@***.***>:

**Comment by o0shojo0o** [comment]
Ach bei den Datenpunkten...

Nein die kannst du als User nicht setzen.
Auch solltest du das nicht machen da dies eigentlich für den Adapter vorbehalten sind. Daher sind die auch nur als Experte zu ändern.

Also nein das werde ich nicht einbauen.

**Comment by Hirsch-DE** [comment]
Man könnte doch setObjectNotExists verwenden, damit nur der state erstellt wird, wenn er nicht vorhanden ist.


22.07.2023 13:24:29 Dennis Rathjen ***@***.***>:

**Comment by Hirsch-DE** [comment]
Vielleicht noch mal zur Klarstellung, es geht um den Namen, welcher im Admin ganz ohne Experten-Modus gesetzt werden kann nach eigenen Vorstellungen (common.name).
Das sollte der Adapter nur beim Anlegen setzen, dann aber nicht die Usereinstellungen wieder verändern!
