### ISSUE TITLE
MPPT data form "openDTU on Battery" in ioBroker

### ISSUE THREAD

**Issue by CosmicGMX** [o0shojo0o/ioBroker.opendtu#84]
Thanks for your well working ioBroker interface for the openDTU. Now i have add a 2nd instanz for a new "openDTU on Battery" to ioBroker. Is there a chance to get also MPPT Data (Victron) into ioBroker ? Up to now ther are only Data from Hoymiles.

**Comment by o0shojo0o** [comment]
Currently only the original OpenDTU project is supported, and no forks of it.

**Comment by o0shojo0o** [comment]
Can't you get the data with this adapter? 
https://github.com/derAlff/ioBroker.ve

**Comment by o0shojo0o** [comment]
Duplicate of https://github.com/o0shojo0o/ioBroker.opendtu/issues/51
