### ISSUE TITLE
opendtu.0.total.yieldday wird nicht genullt 

### ISSUE THREAD

**Issue by Grothesk242** [o0shojo0o/ioBroker.opendtu#96]
Der Datenpunkt opendtu.0.total.yieldday wird nicht um 0 Uhr genullt, obwohl ich das so in openDTU eingestellt habe und im Dashboard von openDTU wird a auch korrekt um Mitternacht genullt.

**Comment by o0shojo0o** [comment]
Ja ich sehe grad das die DTU aber noch mal nach 00:00 Uhr den Wert meldet ... 
Auch nur wenn die Nullung aktiviert ist ... 
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/19333515/9cc2a3ad-63a4-4c21-b124-82529bb2d9bd)

**Comment by Grothesk242** [comment]
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/57298681/4bfb0626-b0c3-4216-9c58-ab0797afe284)
Den Null-Knick hab ich da auch...

**Comment by o0shojo0o** [comment]
Ja da kommen nach 00:00 Uhr ein mal die alten Daten, und das schreibt der Adapter nieder.
Vielleicht kann der @tbnobody noch mal prüfen ob über den Websocket nach 00:00 Uhr der "alte" Wert kommt?

**Comment by Grothesk242** [comment]
Soll/kann ich was anders einstellen? Die Nullung auf der openDTU aus?

**Comment by o0shojo0o** [comment]
Ja, wenn due die Nullung im OpenDTU ausstellst sollte das nicht mehr passieren.

**Comment by tbnobody** [comment]
> Ja ich sehe grad das die OpenDTU aber noch mal nach 00:00 Uhr den Wert meldet ... Auch nur wenn die Nullung aktiviert ist ...

Es sieht ja auch  so aus als würde der Wert bei dir nur kurz auf 0 verweilen und dann wieder nach oben gehen und dort auch bleiben. Das kann ich hier absolut nicht nachvollziehen

![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/1753222/87016ad2-d8f1-4161-8323-3409cf4dc1c7)

**Comment by Grothesk242** [comment]
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/57298681/dfbd3440-b7b3-4326-b31b-c6a884226aa0)
und
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/57298681/817f7231-49d7-4c2b-8a8c-f5738c2c02fc)
wäre aber dann richtig für eine Nullung?

**Comment by o0shojo0o** [comment]
Ok, dann suche ich mal weiter. 
Danke für deine Rückmeldung @tbnobody!

**Comment by Grothesk242** [comment]
Ja, hat geholfen. Fällt jetzt um Mitternacht auf Null und bleibt da bis zum Inverterstart.

**Comment by Grothesk242** [comment]
Doch nicht gelöst. 
Ich kapier es nicht. Direkt in der openDTU wird nicht mehr genullt, es wird jetzt um 0:10 der (Vor)Tagesertrag angezeigt. 
Auf der Ulanzi Uhr wird Null angezeigt. Und der E-Chart-Graph ist kurz auf Null gewesen und jetzt wieder hoch auf dem (Vor)-Tagesertrag. Wo kommen die vollkommen unterschiedlichen Werte her?

**Comment by o0shojo0o** [comment]
Das kann ich so nicht nachvollziehen,
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/19333515/b7ab5765-a7d6-4362-b6fa-6dfa1ae3f3da)

Auch der Adapter merkt sich keine Werte, daher könnte er den auch nicht erneut schreiben, kann es sein das bei dir ein Script mitmischt?

**Comment by o0shojo0o** [comment]
Ich habe mir mal eine Logausgabe dafür gebaut um zu sehen wann was da kommt. 
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/19333515/540e86af-d1c7-46e5-9566-c9eac8bd489e)
Also schauen wir morgen mal was da rumkommt..

**Comment by o0shojo0o** [comment]
@tbnobody das Publish Verhalten über die Websocket API hat sich geändert, ist das gewollt?
Weil vorher wurden nur geänderte Werte publisht.
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/19333515/c615fc49-ef7c-4e4d-80bb-b157694dea25)

**Comment by o0shojo0o** [comment]
Ok Ich habe da ein Bug, werde mir da was einfallen lassen!

**Comment by Grothesk242** [comment]
Wenn die Werte direkt von openDTU kommen bräuchte man ja auch nicht im Adapter nullen.

**Comment by o0shojo0o** [comment]
> Wenn die Werte direkt von openDTU kommen bräuchte man ja auch nicht im Adapter nullen.

Ja genau, das gab es halt nicht vorher, daher hat es der Adapter gemacht.

**Comment by o0shojo0o** [comment]
Kannst mal vom Git installieren und testen? 
Die Nullung muss nun von OpenDTU gemacht werden, der Adapter macht es nun nicht mehr !

**Comment by o0shojo0o** [comment]
Ok, habe 7 Rückmeldungen das es nun läuft 👍

**Comment by Grothesk242** [comment]
Bin zwar spät dran, aber hier läuft es auch nun! :-)
