### ISSUE TITLE
Daten werden nicht richtig Ausgelesen

### ISSUE THREAD

**Issue by Continueless** [o0shojo0o/ioBroker.opendtu#97]
**Describe the bug**  
Spannung, Storm und Leistung werden manchmal mit 0 zurück gegeben, wodurch einige Daten fehlen im Graph

**To Reproduce**  
kommt immer wieder sporadisch

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 0.17
 - JS-Controller version: 5.0.12
 - Node version: 16
 - Operating system: ubuntu 22.04

**Additional context**

**Comment by o0shojo0o** [comment]
Das kann ich so nicht bestätigen, sicher das die Verbindung zu deinen Inverter nicht weg war? 
Weil dann setzt OpenDTU die werte auf 0.

**Comment by o0shojo0o** [comment]
Ich habe in der aktuellen git Version eine Option namens `Set the states to 0 if the inverter is not accessible` hinzugefügt die du abschalten kannst, so das die Nullung nicht mehr von Adapter gemacht wird wenn der Inverter offline geht. 

So werden nur stumpft die Daten von der OpenDTU in den States geschoben .

**Comment by Continueless** [comment]
Das bedeutet, daß es vom iobroker aus nicht einstellbar ist ? Oder was meinst du genau ?

Wenn es denn nicht aus iobroker geht,könntest du das dann hinzufügen ? Bin sicher nicht der einzige, der einen Nutzen salon hätte. Einzig andere Möglichkeit die ich habe, wäre das ich 0 Werte ignoriere wenn sie kommen.

**Comment by o0shojo0o** [comment]
Sorry jetzt kann ich dir nicht mehr folgen. 
Ich habe nur die Logik vom Adapter für das nullen von Inverter Werten abschaltbar über die Einstellungen gemacht.

**Comment by Continueless** [comment]
Achso. Also kann man es in den Einstellungen direkt im iobroker nun abschalten ?
Ist das bereits ein stable Release ?

**Comment by Continueless** [comment]
Also es geht um diese nullen. Nur das wir nun nicht aneinader vorbei reden. Es geht nicht darum das yieldday um 0 Uhr auf 0 gesetzt wird.
Der Adapter soll also am Tag praktisch wenn 0 vom Inverter kommt das ignorieren bis wieder ein verlässlicher Wert kommt. Dies ist bei der Abfrage über mqtt so.

<img width="1233" alt="Screenshot 2023-09-29 121428" src="https://github.com/o0shojo0o/ioBroker.opendtu/assets/124534478/398bd0b8-0455-4d59-b688-b7a441b9821f">

**Comment by o0shojo0o** [comment]
> Also es geht um diese nullen. Nur das wir nun nicht aneinader vorbei reden. Es geht nicht darum das yieldday um 0 Uhr auf 0 gesetzt wird. 

Das wird in der aktuellen Adapter Version durch den OpenDTU  gesteuert. 

> Der Adapter soll also am Tag praktisch wenn 0 vom Inverter kommt das ignorieren bis wieder ein verlässlicher Wert kommt. Dies ist bei der Abfrage über mqtt so.

Nein das ist bei MQTT und über Wesocket gleich, nur der Adpater hat da noch etwas an Logik drinnen was Du aber durch die neue Option von Adapter deaktivierst kannst (für z.B. instabilere Verbindungen)

**Comment by Continueless** [comment]
Ich hab es probiert. Es ist bei mqtt anders. Bei mqtt behält er den Wert bei, bis ein neuer verlässlicher Wert kommt.

Wo genau kann ich die von dir benannte Einstellung machen ?

**Comment by o0shojo0o** [comment]
> Ich hab es probiert. Es ist bei mqtt anders. Bei mqtt behält er den Wert bei, bis ein neuer verlässlicher Wert kommt. Wo genau kann ich die von dir benannte Einstellung machen ?

ioBroker:
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/19333515/b3e981e7-47d7-442c-931e-fbe1c38812f0)

OpenDTU:
![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/19333515/dd16ce5f-ed81-4c5b-aa03-b706611bf863)

**Comment by Continueless** [comment]
Okay. Ich hatte die Version 0.1.7. Da gab es nichts anzuhaken.

Habe nun auf 0.1.8 geupdated. Nun ist nur das Protect self.... zu sehen. Den anderen Punkt auf deinem Bild gibt es bei mir nicht.

**Comment by o0shojo0o** [comment]
Wie ich hier schon [hier](https://github.com/o0shojo0o/ioBroker.opendtu/issues/97#issuecomment-1739927800) habe ich es in der  Git Version hinzugefügt...

**Comment by Continueless** [comment]
okay und wie bekomme ich die git version ins iobroker ?

**Comment by Continueless** [comment]
Ich habe es nun 24h getestet und der Adapter macht genau das was er soll.

Vielen Dank das du dich darum überhaupt benühst und das du mir weitergeholfen hast !! Wirklich erstklassig und nicht selbstverständlich !!
