### ISSUE TITLE
Opendtu stellt morgens keine Verbindung mehr her

### ISSUE THREAD

**Issue by Hohenbostler** [o0shojo0o/ioBroker.opendtu#98]
Hallo,

ich habe leider das Problem das morgens die Objekte nicht aktualisiert werden und entsprechend ich keine Werte habe. 
Die Opendtu als solches liefert die richtigen Daten vom WR aber leider kommen diese nicht im iobroker an

Erst ein Neustart der Instanz führt dazu das alles wieder läuft. 

![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/42488069/c49d4c0b-ccad-49f3-a2f8-5fc8035965e4)

**Comment by o0shojo0o** [comment]
Hi, welche Version vom Adapter läuft bei dir denn?

**Comment by Hohenbostler** [comment]
Guten Morgen. 

Ich nutze die Version 0.1.7

**Comment by o0shojo0o** [comment]
Kannst du biste mal auf die Adapter Version 1.0.0 updaten, und bitte auch prüfen das du auch dein OpenDTU aktuell ist.

**Comment by Hohenbostler** [comment]
> Kannst du biste mal auf die Adapter Version 1.0.0 updaten, und bitte auch prüfen das du auch dein OpenDTU aktuell ist.

Danke habe ich mal gemacht. Morgen kann ich mehr berichten.

**Comment by o0shojo0o** [comment]
@Hohenbostler wie schauts aus, ist der Fehler wieder aufgetreten?

**Comment by Hohenbostler** [comment]
> @Hohenbostler wie schauts aus, ist der Fehler wieder aufgetreten?

Guten Morgen. sorry für die späte antwort. Ja der Fehler tritt immer wieder auf. Hier mal zwei Bilder von heute morgen.

Die DTU selbst zeigt richtige Wert an aber die objekte werden nicht aktualisiert.

Meine Vermutung -> Wenn die Opendtu nachts über das Web nicht erreichbar ist ( warum das auch immer passiert ) friert die Instanz ein und aktualisiert sich nicht mehr. 


![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/42488069/1e11e0b6-bc39-438d-87f7-c9852f170d57)

![image](https://github.com/o0shojo0o/ioBroker.opendtu/assets/42488069/c8adabc8-c301-4133-82da-0351ce3a8463)
